linters:
  enable:
    - gofmt
    - goimports
    - govet
    - golint
    - errcheck
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: authentication

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck